# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.provider "virtualbox" do |v|
    v.memory = 256
    v.cpus = 1
  end

  config.vm.define "vm1" do |vm1|
    vm1.vm.box = "centos/7"
    vm1.vm.provision "file", source: "source1.txt", destination: "destination1.txt"
  end
  config.vm.define "vm2" do |vm2|
    vm2.vm.box = "centos/7"
    vm2.vm.provision "file", source: "source2.txt", destination: "destination2.txt"
  end
end
